apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
    group: example
spec:
  replicas: 3
  selector:
#    matchLabels:
#      app: app
    matchExpressions:
      - { key: app, operator: In, values: ["app"] }
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mziemianek/kub-first-app

