apiVersion: v1
kind: Service
metadata:
  name: app-deployment
  labels:
    group: example
spec:
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
