version: '3.8'
services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated  # dalegated improves performance
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan: 
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
  npm:
    build:
      context: ./docker
      dockerfile: npm.dockerfile
    volumes:
      - ./src:/var/www/html
